#!/bin/bash
set -e

# configure php additions.ini
cat /usr/share/nginx/html/index.html.template \
  | envsubst '${ROLL_SERVICE_DOMAIN} ${ROLL_VERSION}' \
  | tee /usr/share/nginx/html/index.html

# Start Nginx
/docker-entrypoint.sh nginx -g 'daemon off;'
