#!/usr/bin/env bash
[[ ! ${ROLL_DIR} ]] && >&2 echo -e "\033[31mThis script is not intended to be run directly!\033[0m" && exit 1

ROLL_ENV_PATH="$(locateEnvPath)" || exit $?
loadEnvConfig "${ROLL_ENV_PATH}" || exit $?

STORES_JSON="${ROLL_ENV_PATH}/.roll/stores.json"
ROLL_ENV_YML="${ROLL_ENV_PATH}/.roll/roll-env.yml"
NGINX_MAP_DIR="${ROLL_ENV_PATH}/.roll/nginx"
NGINX_MAP_FILE="${NGINX_MAP_DIR}/stores.map"

function show_help() {
    echo "Usage: roll multistore <command>"
    echo ""
    echo "Commands:"
    echo "  init      Generate configs from .roll/stores.json and sign SSL certificates"
    echo "  refresh   Regenerate configs from .roll/stores.json (no SSL signing)"
    echo "  list      Show current store configuration"
    echo "  help      Show this help message"
    echo ""
    echo "Configuration:"
    echo "  Create .roll/stores.json with hostname to store code mapping:"
    echo ""
    echo '  {'
    echo '    "stores": {'
    echo '      "store-nl.test": "store_nl",'
    echo '      "store-be.test": "store_be",'
    echo '      "main.test": ""'
    echo '    },'
    echo '    "run_type": "store"'
    echo '  }'
    echo ""
    echo "Generated files:"
    echo "  .roll/roll-env.yml     - Docker Compose override for Traefik routing"
    echo "  .roll/nginx/stores.map - Nginx hostname to store code mapping"
}

function check_stores_json() {
    if [[ ! -f "${STORES_JSON}" ]]; then
        fatal "Missing ${STORES_JSON}. Please create it first. Run 'roll multistore help' for format."
    fi

    if ! command -v jq &> /dev/null; then
        fatal "jq is required for parsing JSON. Please install it: brew install jq"
    fi
}

function get_all_hostnames() {
    jq -r '.stores | keys[]' "${STORES_JSON}"
}

function get_store_code() {
    local hostname="$1"
    jq -r --arg h "$hostname" '.stores[$h] // ""' "${STORES_JSON}"
}

function get_run_type() {
    jq -r '.run_type // "store"' "${STORES_JSON}"
}

function escape_hostname_for_regex() {
    echo "$1" | sed 's/\./\\\\./g'
}

function generate_nginx_map() {
    info "Generating nginx store mapping..."

    mkdir -p "${NGINX_MAP_DIR}"

    local run_type
    run_type=$(get_run_type)

    cat > "${NGINX_MAP_FILE}" <<EOF
# AUTO-GENERATED by roll multistore - do not edit manually
# Regenerate with: roll multistore refresh

map \$http_host \$mage_run_code {
EOF

    while IFS= read -r hostname; do
        local store_code
        store_code=$(get_store_code "$hostname")
        local escaped_hostname
        escaped_hostname=$(escape_hostname_for_regex "$hostname")

        if [[ -n "$store_code" ]]; then
            echo "    ~*^(app\\.)?${escaped_hostname}\$  ${store_code};" >> "${NGINX_MAP_FILE}"
        else
            echo "    # ${hostname} - uses default store code" >> "${NGINX_MAP_FILE}"
        fi
    done < <(get_all_hostnames)

    cat >> "${NGINX_MAP_FILE}" <<EOF
    default '';
}

map \$http_host \$mage_run_type {
    default ${run_type};
}
EOF

    success "Generated ${NGINX_MAP_FILE}"
}

function generate_roll_env_yml() {
    info "Generating roll-env.yml..."

    mkdir -p "${ROLL_ENV_PATH}/.roll"

    # Build Traefik host rules
    local traefik_rules=""
    local first=true

    while IFS= read -r hostname; do
        if [[ "$first" == "true" ]]; then
            first=false
        else
            traefik_rules+=" || "
        fi
        traefik_rules+="HostRegexp(\`{subdomain:.+}.${hostname}\`) || Host(\`${hostname}\`)"
    done < <(get_all_hostnames)

    # Build extra_hosts entries
    local extra_hosts=""
    while IFS= read -r hostname; do
        extra_hosts+="      - \"${hostname}:\${TRAEFIK_ADDRESS:-0.0.0.0}\"\n"
    done < <(get_all_hostnames)

    cat > "${ROLL_ENV_YML}" <<EOF
# AUTO-GENERATED by roll multistore - do not edit manually
# Regenerate with: roll multistore refresh

services:
  nginx:
    labels:
      - traefik.http.routers.\${ROLL_ENV_NAME}-nginx.rule=
          HostRegexp(\`{subdomain:.+}.\${TRAEFIK_DOMAIN}\`) || Host(\`\${TRAEFIK_DOMAIN}\`)
          || ${traefik_rules}
    volumes:
      - ./.roll/nginx/stores.map:/etc/nginx/default.d/stores.map:ro

  php-fpm:
    extra_hosts:
$(echo -e "$extra_hosts" | sed 's/^//')
  php-debug:
    extra_hosts:
$(echo -e "$extra_hosts" | sed 's/^//')
EOF

    success "Generated ${ROLL_ENV_YML}"
}

function sign_certificates() {
    info "Signing SSL certificates for all hostnames..."

    local hostnames=()
    while IFS= read -r hostname; do
        hostnames+=("$hostname")
    done < <(get_all_hostnames)

    if [[ ${#hostnames[@]} -gt 0 ]]; then
        "${ROLL_DIR}/bin/roll" sign-certificate "${hostnames[@]}"
        success "SSL certificates signed for: ${hostnames[*]}"
    fi
}

function list_stores() {
    if [[ ! -f "${STORES_JSON}" ]]; then
        echo "No stores.json found at ${STORES_JSON}"
        return
    fi

    echo "Store Configuration from ${STORES_JSON}:"
    echo ""
    echo "Run Type: $(get_run_type)"
    echo ""
    printf "%-30s %-20s\n" "Hostname" "Store Code"
    printf "%-30s %-20s\n" "--------" "----------"

    while IFS= read -r hostname; do
        local store_code
        store_code=$(get_store_code "$hostname")
        if [[ -z "$store_code" ]]; then
            store_code="(default)"
        fi
        printf "%-30s %-20s\n" "$hostname" "$store_code"
    done < <(get_all_hostnames)

    echo ""

    if [[ -f "${ROLL_ENV_YML}" ]]; then
        success "roll-env.yml: EXISTS"
    else
        warning "roll-env.yml: MISSING (run 'roll multistore init')"
    fi

    if [[ -f "${NGINX_MAP_FILE}" ]]; then
        success "nginx/stores.map: EXISTS"
    else
        warning "nginx/stores.map: MISSING (run 'roll multistore init')"
    fi
}

# Main command handler
case "${ROLL_PARAMS[0]}" in
    init)
        check_stores_json
        generate_nginx_map
        generate_roll_env_yml
        sign_certificates
        echo ""
        success "Multistore configuration initialized!"
        info "Run 'roll env up' to apply the changes."
        ;;
    refresh)
        check_stores_json
        generate_nginx_map
        generate_roll_env_yml
        echo ""
        success "Multistore configuration refreshed!"
        info "Run 'roll env restart nginx' to apply the changes."
        ;;
    list)
        list_stores
        ;;
    help|--help|-h|"")
        show_help
        ;;
    *)
        fatal "Unknown command: ${ROLL_PARAMS[0]}. Run 'roll multistore help' for usage."
        ;;
esac
