services:
  elasticvue:
    image: cars10/elasticvue
    hostname: "${ROLL_ENV_NAME}-elasticvue"
    labels:
      - traefik.enable=true
      - traefik.http.routers.${ROLL_ENV_NAME}-elasticvue.rule=Host(`elasticvue.${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.${ROLL_ENV_NAME}-elasticvue.tls=true
      - traefik.http.services.${ROLL_ENV_NAME}-elasticvue.loadbalancer.server.port=8080
      - traefik.docker.network=${ROLL_ENV_NAME}_default
    environment:
      - ELASTICVUE_CLUSTERS=[{"name":"${ROLL_ENV_NAME}","uri":"https://elasticsearch.${TRAEFIK_DOMAIN}"}]
