version: "3.9"
services:
  php-fpm:
    depends_on:
      - mongodb

  mongodb:
    hostname: "${ROLL_ENV_NAME}-mongodb"
    image: ${ROLL_IMAGE_REPOSITORY}/mongo:${MONGODB_VERSION:-7}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_PASSWORD:-app}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_USER:-app}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-app}
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
