name: Docker Image MailHog
on:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - images/.trigger
      - images/mailhog/**
      - .github/workflows/*mailhog*

jobs:
  mailhog:
    name: MailHog
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v4
        with:
          context: images/mailhog
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: docker.io/rollupdev/mailhog:latest
        if: ${{ !env.ACT && github.ref == 'refs/heads/main'}}

      - uses: docker/build-push-action@v4
        with:
          context: images/mailhog
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/rolldev-mailhog:latest
        if: ${{ !env.ACT && github.ref == 'refs/heads/alpha'}}
