name: Docker Image Redis
on:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - images/.trigger
      - images/redis/**
      - .github/workflows/*redis*

jobs:
  redis:
    name: Redis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.2"
          - "4.0"
          - "5.0"
          - "6.0"
          - "6.2"
          - "7.0"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v4
        with:
          context: images/redis
          platforms: linux/amd64,linux/arm64
          build-args: REDIS_VERSION=${{ matrix.version.from }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: docker.io/rollupdev/redis:${{ matrix.version.tag }}
        if: ${{ !env.ACT && github.ref == 'refs/heads/main'}}

      - uses: docker/build-push-action@v4
        with:
          context: images/redis
          platforms: linux/amd64,linux/arm64
          build-args: REDIS_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/rolldev-redis:${{ matrix.version }}
        if: ${{ !env.ACT && github.ref == 'refs/heads/alpha'}}